name: Validate JSON

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt install -y jq

      - name: Validate json structure
        run: |
          if ! jq 'all(.[]; has("id") and has("name") and has("url"))' members.json; then
            echo "JSON validation failed: not all elements have 'id', 'name', and 'url'"
            exit 1
          fi
